version: "3"

services:
  php:
    build:
      context: ./api
    container_name: symfony_docker-php
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/symfony_docker
    restart: on-failure