version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./api
    container_name: symfony_docker-php
    ports:
      - 9000:9000
    volumes:
      - ./api:/var/www/symfony_docker
    restart: on-failure